id: P007963
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6658
  title: ཞེ་སའི་ལག་དེབ་བླི་གསར་དགའ་སྟོན།
  author: ''
  volumes:
    4882104d7f044260b0d58d9ca5c35d23:
      image_group_id: I3CN6660
      title: Volume 1 of zhe sa'i lag deb bli gsar dga' ston/
      volume_number: 1
      total_pages: 349
      base_file: v001.txt
