id: P007963
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6658
  title: ཞེ་སའི་ལག་དེབ་བླི་གསར་དགའ་སྟོན།
  author: ''
  volumes:
    4fe88f23bb3d43dc9b61cb7c7aeb5639:
      image_group_id: I3CN6660
      title: ''
      volume_number: 1
      total_pages: 349
ebook_metadata:
  title: ཞེ་སའི་ལག་དེབ་བླི་གསར་དགའ་སྟོན།
  author: ''
  sku: P007963
  cover: cover.jpg
  layers:
  - pagination
